# Define a method to resolve the path of react_native_pods.rb using node
require 'open3'

$RNMapboxMapsImpl = 'mapbox'

def resolve_react_native_pods_rb
  stdout, stderr, status = Open3.capture3("node", "-p", <<~JS, __dir__)
    require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )
  JS

  unless status.success?
    raise stderr
  end

  stdout.strip
end

# Require the resolved path
require resolve_react_native_pods_rb

# Add the permissions setup script
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Toilet2Go' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Explicitly set the MapboxMaps and Turf versions to resolve conflicts
  pod 'MapboxMaps', '~> 10.18.2'
  pod 'Turf', '~> 2.8.0'

  # Add react-native-permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # Call setup_permissions with the required permissions
  setup_permissions([
    'LocationWhenInUse', # Add this line to include the LocationWhenInUse permission
    # Other permissions you might need
  ])

  target 'Toilet2GoTests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
